# Generated by Django 2.2.7 on 2020-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191119_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The max length of your description is 1000 symbols.', max_length=1000, null=True),
        ),
    ]
