# Generated by Django 2.2.7 on 2019-11-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_like',
        ),
    ]
