# Generated by Django 2.2.7 on 2019-11-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20191128_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='comment_like',
        ),
    ]
