# Generated by Django 2.2.7 on 2020-04-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20191128_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-created_at',)},
        ),
    ]
